### ISSUE TITLE
time-series sensor data unbeliebably slow

### ISSUE THREAD

**Issue by nganju-usgs** [USGS-CMG/usgs-cmg-portal#175] opened 2016-03-03 19:21 UTC
Tried to graph time-series data from a sensor and a model (not a long time-series, about 2 months) and still spinning. what governs these speeds? too slow for any functional purpose right now.

**Comment by shane-axiom** [comment] 2016-03-03 20:12
Spot checked a few models and they seemed fine. Tested a Sandy gauge sensor and found a sensor service error, probably introduced yesterday. Good news is that the issue is a bug and not a slow system. We're working on a fix currently.

Thanks for reporting. In the future, please include links or references to specific datasets when reporting problems as it greatly reduces the time it takes for us to track them down.

**Comment by nganju-usgs** [comment] 2016-03-03 20:27
this has been spinning for 5 minutes
[image: Inline image 1]

On Thu, Mar 3, 2016 at 3:12 PM, Shane StClair <notifications@github.com>
wrote:

> Spot checked a few models and they seemed fine. Tested a Sandy gauge
> sensor and found a sensor service error, probably introduced yesterday.
> Good news is that the issue is a bug and not a slow system. We're working
> on a fix currently.
>
> Thanks for reporting. In the future, please include links or references to
> specific datasets when reporting problems as it greatly reduces the time it
> takes for us to track them down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/175#issuecomment-191942457>
> .
>



-- 
Neil K. Ganju
U.S. Geological Survey | Coastal and Marine Geology
384 Woods Hole Road | Woods Hole, MA 02543-1598
nganju@usgs.gov | business hours: (508) 457 2252 | after hours: (916) 207
2206
http://woodshole.er.usgs.gov/project-pages/estuaries/

**Comment by shane-axiom** [comment] 2016-03-03 20:48
What's "this"?

**Comment by nganju-usgs** [comment] 2016-03-03 21:15
see attached

On Thu, Mar 3, 2016 at 3:48 PM, Shane StClair <notifications@github.com>
wrote:

> What's "this"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/175#issuecomment-191956206>
> .
>



-- 
Neil K. Ganju
U.S. Geological Survey | Coastal and Marine Geology
384 Woods Hole Road | Woods Hole, MA 02543-1598
nganju@usgs.gov | business hours: (508) 457 2252 | after hours: (916) 207
2206
http://woodshole.er.usgs.gov/project-pages/estuaries/

**Comment by shane-axiom** [comment] 2016-03-03 21:22
Sorry, there's no attachment?

**Comment by nganju-usgs** [comment] 2016-03-03 21:24
are they getting scrubbed? attached again...

On Thu, Mar 3, 2016 at 4:22 PM, Shane StClair <notifications@github.com>
wrote:

> Sorry, there's no attachment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/175#issuecomment-191969970>
> .
>



-- 
Neil K. Ganju
U.S. Geological Survey | Coastal and Marine Geology
384 Woods Hole Road | Woods Hole, MA 02543-1598
nganju@usgs.gov | business hours: (508) 457 2252 | after hours: (916) 207
2206
http://woodshole.er.usgs.gov/project-pages/estuaries/

**Comment by shane-axiom** [comment] 2016-03-03 22:08
Yeah, no attachment again. The sensor issue is fixed now, they're loading quickly again.

**Comment by rsignell-usgs** [comment] 2016-03-04 19:37
Confirmed that sensor data is fast again.

**Closed** 2016-03-04 19:37 UTC
