### ISSUE TITLE
run076 Barnegat Bay model time series data do not display

### ISSUE THREAD

**Issue by zdefne-usgs** [USGS-CMG/usgs-cmg-portal#157] opened 2016-02-06 04:56 UTC
When clicked on a layer (e.g. free surface) pop-up window for the time series is not displayed. Something different than the other models where time series are displayed fine is that this model is a restart run. The output files start one month after the model start date on the input file...

**Comment by rsignell-usgs** [comment] 2016-02-10 03:25
Confirmed.   Clicking a point on 
http://cmgdata.usgsportals.net/#map?p=proj3857&b=google_hybrid&page=1&tagId=&q=&lg=a0142836-0a04-49c0-a054-6b70ff5893a9&z=10&ll=39.79358%2C-74.22003
pops up a box with the location, but then just spins...

![2016-02-09_22-22-20](https://cloud.githubusercontent.com/assets/1872600/12937957/0c0002be-cf7c-11e5-97cd-e091f72e599e.jpg)

**Comment by kwilcox** [comment] 2016-02-10 04:03
Going to hold off on looking into this... we will be moving to using NCSS for remote time series in the next week or so.

**Comment by rsignell-usgs** [comment] 2016-02-23 14:19
Although [the portal can now use NCSS for time series extraction[(https://github.com/USGS-CMG/usgs-cmg-portal/issues/127#issuecomment-187380915) , I just tried and times series on this dataset is still isn't working. 

http://cmgdata.usgsportals.net/#module-metadata/0d0bc16b-90f0-3976-ae4a-9906a750497e/d6be53c0-9e4c-419e-8d81-77b463822e44

Even though the NCSS service seems to be alive and well, for example:
http://geoport-dev.whoi.edu/thredds/ncss/clay/usgs/users/zdefne/run076/his/00_dir_roms_display.ncml?var=zeta&latitude=39.75&longitude=-74.1&time_start=2012-10-29T00%3A30%3A00Z&time_end=2012-11-02T00%3A00%3A00Z&vertCoord=&accept=csv

**Comment by kwilcox** [comment] 2016-02-23 14:47
Should be good, try again

**Comment by rsignell-usgs** [comment] 2016-02-23 15:03
Yes, time series is now working.  I notice, however, that the map is in degrees F and the time series plot is in degrees C.   Should I close this and open a new ticket for that?

![2016-02-23_10-01-31](https://cloud.githubusercontent.com/assets/1872600/13255563/b02bcc40-da14-11e5-8069-bc240a0f5ffd.jpg)

**Comment by kwilcox** [comment] 2016-02-23 15:44
Yes

**Closed by kwilcox** 2016-02-23 15:44 UTC
