### ISSUE TITLE
Allow user complete control over y-axis limits on timeseries plots

### ISSUE THREAD

**Issue by kwilcox** [USGS-CMG/usgs-cmg-portal#108] opened 2015-09-14 19:51 UTC
Currently when restricting the time range on a time series plot, there is no way to rescale the Y axis limit (e.g plot remains scaled by original data range no matter what).  We should have a button to rescale the Y axis based on the limits in the graph.

**Comment by nganju-usgs** [comment] 2015-12-16 15:34
not sure if this is related, but for some of our sensor data fill values appear, and with no rescaling can't see the actual data. It also looks like fill values are being interpolated to the resampling interval, resulting in weird values like 343485293423459.23 (for example)
![image](https://cloud.githubusercontent.com/assets/8660183/11845159/832bd8ee-a3e0-11e5-9948-4f81032db6ca.png)

**Comment by rsignell-usgs** [comment] 2016-02-02 14:15
@kwilcox, we really need to be able to set the limits on the y axis of these time series plots (not just autorescale).   And this should be a top priority for milestone 1, not milestone 2.   
Without it, plots of data with a large dynamic range (like https://github.com/USGS-CMG/usgs-cmg-portal/issues/117#issuecomment-178511778) are useless.
Is it really truly hard to implement?

**Comment by rsignell-usgs** [comment] 2016-02-27 13:07
In my opinion, we can't release the v1.0 portal without this ability to rescale the y axis of the time series plots. 
@nganju-usgs , @jcwarner-usgs, what do you think?

**Comment by rsignell-usgs** [comment] 2016-02-29 13:21
Yet another reason we need the user to be able to set the limits.   This Florida USGS dataset 
http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c
has only one label:  0.0:
![2016-02-29_8-17-25](https://cloud.githubusercontent.com/assets/1872600/13395526/557886d2-debd-11e5-8cda-889448520026.png)

**Comment by nganju-usgs** [comment] 2016-02-29 14:18
agreed

On Sat, Feb 27, 2016 at 8:07 AM, Rich Signell <notifications@github.com>
wrote:

> In my opinion, we can't release the v1.0 portal without this ability to
> rescale the y axis of the time series plots.
> @nganju-usgs <https://github.com/nganju-usgs> , @jcwarner-usgs
> <https://github.com/jcwarner-usgs>, what do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/108#issuecomment-189635750>
> .
>



-- 
Neil K. Ganju
U.S. Geological Survey | Coastal and Marine Geology
384 Woods Hole Road | Woods Hole, MA 02543-1598
nganju@usgs.gov | business hours: (508) 457 2252 | after hours: (916) 207
2206
http://woodshole.er.usgs.gov/project-pages/estuaries/

**Comment by rsignell-usgs** [comment] 2016-03-11 15:08
Just to be clear, in addition to a  "rescale"="autoscale to time window" button, we want to be able to set the lower and upper limits of the y axis as well (typein values in the GUI).    

I've changed the title of this issue to correct this.   

 I'd have brought in Brian Stone here but I don't know what his github handle is.

**Comment by shane-axiom** [comment] 2016-03-11 20:19
@akbstone

**Comment by rsignell-usgs** [comment] 2016-03-15 17:34
@akbstone, what's your assessment of the difficulty in completing this task?
In other words, what's the ETA?

**Comment by akbstone** [comment] 2016-03-15 19:05
@rsignell-usgs - I'm including this in the long running time series improvements (https://github.com/USGS-CMG/usgs-cmg-portal/issues/129) slated for V2.  I may be able to plug this code in to V1 when it's ready.. likely 2 weeks out.

**Comment by rsignell-usgs** [comment] 2016-03-15 21:35
@akbstone, okay, really looking forward to this.    Two weeks is okay, but if V2 turns out to take significantly longer, than it would be really useful to get the y-axis control into V1.   Thanks!

**Comment by rsignell-usgs** [comment] 2016-03-28 15:39
@akbstone, how are we doing on this blocker issue for V1.0?

**Comment by akbstone** [comment] 2016-03-28 15:46
@rsignell-usgs  - still in progress. Hoping to have something to look at this week.

**Comment by rsignell-usgs** [comment] 2016-04-01 01:51
@akbstone, can you give us some idea of what the new functionality will be?  
Anything would be okay:  screenshot, mock-up, text description.

**Comment by akbstone** [comment] 2016-04-01 16:23
@richsignell

Upgrades to be included

Axis control:

- Ability to autoscale y axis 
- X and Y axis controls that allow finer control when small span selected

Handling of time series':

- Large spans are binned on year/month/week/day based on span shown.  When binned, mean line, 10 and 90 percentile lines (https://github.com/mbostock/d3/wiki/Arrays#d3_quantile) and min/max lines shown. At close zoom levels, data is no longer binned. There's a 'records' feature that shows the record min/max for day/week/month of year, but it's kind of slow.. will need to experiment with it.

**Comment by rsignell-usgs** [comment] 2016-04-01 16:54
@akbstone , thanks for the update.   When's the latest ETA for something to see?

**Comment by akbstone** [comment] 2016-04-07 04:39
@rsignell-usgs 

You can preview this functionality here:
http://axiomdatascience.com/files/time_series/

- To adjust y scale, unselect the 'Auto scale?' checkbox.
- Use the dropdown menu at the top to browse a few different time series'. Let me know if there are any data sets in particular you'd like to preview immediately.
- The Prov Air Temp time series takes a while to process. Selecting 'All' in the Binners dropdown might crash the browser if the full time series is in view.
- The 'Binners' dropdown is meant for debug and likely won't be a part of the mapping application initially.

I'll begin integrating this functionality in to the main mapping application tomorrow.

**Comment by rsignell-usgs** [comment] 2016-04-07 12:52
@akbstone, pretty darn cool!   I played around with this quite a bit with the different datasets, and everything seemed to work well.   Nice to have the progress info when loading data, and I have to admit I can see the use for the binning, especially for long time series like the Providence 16 year air temps.    

It seems that hovering over or clicking on the time series no longer pops up any information, but is that because that comes when integrate it with the main mapping application?

I can't find much to else suggest, except that *perhaps* it would nice to be able to have type-in controls to set the y-limits in addition to the slider (e.g. click the end of the slider, get a type-in popup?).   What do you think @nganju-usgs and @jcwarner-usgs, do we need type-ins, or is the slider sufficient?

And one very minor question:  In the plot below, I think the dashed lines are all time maximum and minimums for the 16 year record, is that right?    If so, how can the weekly max value exceed that?  (I'm probably interpreting this wrong, right?)
![2016-04-07_8-41-03](https://cloud.githubusercontent.com/assets/1872600/14351572/0a7cae66-fc9e-11e5-83c9-1d5c28d33237.jpg)

**Comment by nganju-usgs** [comment] 2016-04-07 14:00
i think the functionality is great as is, may want to default to "all" for the binner if the data set is < 1 year long?

**Comment by rsignell-usgs** [comment] 2016-04-07 14:19
@nganju-usgs :+1: 
Our users will be confused by this initial (default) view:
![2016-04-07_10-16-28](https://cloud.githubusercontent.com/assets/1872600/14354091/f70ef2d8-fca9-11e5-92d6-34c94533764f.jpg)

They expect to see this:
![2016-04-07_10-16-05](https://cloud.githubusercontent.com/assets/1872600/14354137/29bdc862-fcaa-11e5-892d-435066397e0b.jpg)

**Comment by kwilcox** [comment] 2016-04-07 19:41
@rsignell-usgs @nganju-usgs All of the values will show up when you are looking at less than 2 months of data when. After some careful analysis between lots of different time-series, this was the happy medium between browser performance, the ability to pick out small spikes in the data, and whatever white papers we could find about how to display time-series. We can't enable a global "1 year to see all" option because of the occasional (but ever more frequent) time-series on sub-second intervals that explode past the limits of modern browsers fairly quickly.

We will be moving to "point" based bins in the future, meaning that sparse time-series may show all of the data for a long period, while dense time-series will show all for a shorter period. It will depend on the number of data points in the time-series.

Regarding users being confused at initially seeing bins... is that necessarily a bad thing? Seeing the image at the bottom might be what most people are used to, but it is really the most meaningful way to view an entire year of data?

**Comment by akbstone** [comment] 2016-04-07 21:24
@rsignell-usgs 

I was able to reproduce the issue you pointed out where a bin passed over the maximum value. This was happening because I was applying smoothing to the high/low value lines. The high now passes through (or touches) the center of the bin during which it occurred.

![image](https://cloud.githubusercontent.com/assets/1093777/14367346/0641abdc-fcc4-11e5-90f2-15e89fc33db2.png)

**Comment by akbstone** [comment] 2016-04-07 21:25
@rsignell-usgs 

Yes, hover functionality will come with app integration.  I'll add type-in functionality to my list.. but probably won't be included initially.

**Comment by emontgomery-usgs** [comment] 2016-04-08 13:49
Shouldn't the gaps be empty?
![image](https://cloud.githubusercontent.com/assets/1771422/14385559/248a12fe-fd6f-11e5-8370-0f67499323d2.png)

**Comment by emontgomery-usgs** [comment] 2016-04-08 14:09
Folks-

In some ways I can see why you want the default to be 1 day averages, but there's not enough description on the display to say what the plot is actually showing.  As someone who works with data a lot, I was able to get an idea of what was probably displayed, but adding a legend is needed to help others.

I feel strongly that the default for datasets shorter than one year (the limit described above for browser optimization) should default to the "all" view.  

Also the 16 years of data at the Providence airport took more than a minute to load, process and display initially.  Too slow to keep the attention of most users, though I applaud the frame at the right showing progress.  Perhaps with large datasets the user should be offered the option of loading subsets for performance.

**Comment by rsignell-usgs** [comment] 2016-04-08 14:19
@akbstone one more suggestion:   
Instead of the initial view showing a checked box that says "auto scale?", have the initial view show the y axis controls with the box unchecked.    That would be more similar to the x axis initial view that shows the sliders.   Best to show folks the capability first, with the option to hide it via autoscale, rather than the other way around.

**Comment by rsignell-usgs** [comment] 2016-04-28 10:34
@akbstone , @kwilcox , I checked today, and the ability to set y limits on time series plots still doesn't seem to exist.   Did someone forget to flip the switch to enable this on the portal?

**Comment by rsignell-usgs** [comment] 2016-06-21 18:19
On April 7, @akbstone said "I'll begin integrating this functionality in to the main mapping application tomorrow."  Where do we stand?

**Comment by akbstone** [comment] 2016-06-22 01:27
@rsignell-usgs 

This is live at a preview url now:

http://cmgdata.usgsportals.net/?use_new_charts=true

Currently, real time and historical sensors get this functionality. I am out of town starting this evening until July 8th.

cc @kwilcox

**Comment by rsignell-usgs** [comment] 2016-06-22 14:18
Hmm, what happened to our suggestions from before about making the default binning be "all" (or actually "none") so that the initial view is of the raw data, and user can choose to bin if they want to?

Looking at this preview capability, it now seems that the user can't even select what binning to do -- it just happens automatically, which is not acceptable.   I expect to see tides here, but see this instead: 
![2016-06-22_6-17-49](https://cloud.githubusercontent.com/assets/1872600/16269965/7cfb4df8-3862-11e6-93b5-d86c8fa99a32.jpg)

**Comment by akbstone** [comment] 2016-07-01 00:21
@rsignell-usgs  - I've updated chart preview:

http://cmgdata.usgsportals.net/?use_new_charts=true

- Binning can now be overridden manually (default to auto - see below)
- Auto binning is determined based on density of data rather than selected time period. Approx. 2500 data points should generally appear.  In the data set you referenced above, the automatic default is now 'all'
- To be released soon: real time sensors will immediately load data for the past 7 days and back load historical data. By default, all real time sensors will show 'all' until expanded after historical data has loaded.

I am reluctant to make 'all' the default as most browsers will start to choke when displaying more than ~ 5k data points. If this is an important feature for longer time series' on the CMG portal, I'll look  in to alternate methods of rendering (canvas).

**Comment by akbstone** [comment] 2016-07-01 00:27
@emontgomery-usgs 

Gaps are now at app preview url:

http://cmgdata.usgsportals.net/?use_new_charts=true#map?p=proj3857&b=google_hybrid&page=1&tagId=&q=time+series&tags=&lg=6878f136-b61e-11e4-a8f5-00265529168c%2C8ccf971e-565c-11e4-9915-00265529168c&z=11&ll=41.77028%2C-71.42143

![image](https://cloud.githubusercontent.com/assets/1093777/16508442/63fc572e-3edf-11e6-81a8-83537ce22507.png)

**Comment by emontgomery-usgs** [comment] 2016-07-01 17:49
@akbstone, @rsignell-usgs 
Great progress with the beta version.  Nice job overall with the binning and autoscaling options!

Of course, I had to go look at some oceanographic data, and picked 859 from West Falmouth Harbor experiment.  The data from 8591wh shows up initially and I was able to blow it up to get this graph 
![image](https://cloud.githubusercontent.com/assets/1771422/16529571/ab1eb176-3f91-11e6-8709-e3244a35035b.png)
The raw data is hourly, which accounts for the "banded" look at this level of enlargement.  I think this is appropriate- no interpolation is done to make it look smoother than it is.  

Why are the original East and North Velocities no longer displayed?  The original data doesn't even have "currents"  that's something the portal computes, and there's little information in just the current speed, without direction.  I don't find the original rose display of direction particularly informative, and understand that's why it's not there now, but we need more than just speed. Thus, separate views of the east and north components provide more information.

Also, when I returned to the page the curtain plot never refreshed.  The underlying data is there because the profile plots are shown. 
![image](https://cloud.githubusercontent.com/assets/1771422/16529755/ad5b3210-3f92-11e6-8672-b6acb303f399.png)

Thanks

**Comment by rsignell-usgs** [comment] 2016-07-19 15:37
The problems above seem to be fixed, with the exception of:
* the "one tick label" problem
* the reporting of depth as "-1m" no matter where the cursor is.  (the speed value displayed nicely tracks the cursor as you wander around in the curtain plot but the depth always reports "-1". 
![2016-07-19_11-02-53](https://cloud.githubusercontent.com/assets/1872600/16956134/30fdb744-4da5-11e6-813d-d6af050ade7b.jpg)

**Comment by akbstone** [comment] 2016-08-03 18:08
@rsignell-usgs  - reporting depth at 1m problem now fixed on preview url.

**Comment by rsignell-usgs** [comment] 2017-01-19 19:21
The default portal now has y-scaling:
![2017-01-19_14-05-45](https://cloud.githubusercontent.com/assets/1872600/22121087/7a5b9e1a-de50-11e6-9d51-b258ed4c0280.jpg)

This closes out [Milestone Version 1.0!](https://github.com/USGS-CMG/usgs-cmg-portal/milestone/1) :tada: :champagne: :tada: :champagne:

**Closed by rsignell-usgs** 2017-01-19 19:22 UTC
